// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Permissions.Infrastructure.Data;

#nullable disable

namespace Permissions.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PermissionsDbContext))]
    partial class PermissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("permissions")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Permissions.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("999b1e1f-502d-4866-bfd8-2c167185558d"),
                            Category = "UserManagement",
                            Description = "Administrative control over View operations on UserManagement user profiles",
                            Name = "UserManagement.View"
                        },
                        new
                        {
                            Id = new Guid("93febb76-5b12-4d44-a0bb-c8ffda461aae"),
                            Category = "UserManagement",
                            Description = "Temporary permission to Create operations on UserManagement configuration settings",
                            Name = "UserManagement.Create"
                        },
                        new
                        {
                            Id = new Guid("a54d7c51-2780-4c69-a192-9723930daa9f"),
                            Category = "UserManagement",
                            Description = "Limited scope for Edit operations on UserManagement reporting modules",
                            Name = "UserManagement.Edit"
                        },
                        new
                        {
                            Id = new Guid("b1d57247-2060-4a47-b96e-04cd12797342"),
                            Category = "UserManagement",
                            Description = "Audit capability for Delete operations on UserManagement user profiles",
                            Name = "UserManagement.Delete"
                        },
                        new
                        {
                            Id = new Guid("993d8062-6118-4edf-9315-e9ca2f65b3be"),
                            Category = "UserManagement",
                            Description = "Audit capability for Approve operations on UserManagement API endpoints",
                            Name = "UserManagement.Approve"
                        },
                        new
                        {
                            Id = new Guid("20face18-4a30-4272-8621-40f21ebadec2"),
                            Category = "UserManagement",
                            Description = "Global access to Reject operations on UserManagement reporting modules",
                            Name = "UserManagement.Reject"
                        },
                        new
                        {
                            Id = new Guid("74664bf8-c992-4fad-bcd7-7cdc81647d3e"),
                            Category = "UserManagement",
                            Description = "Compliance-related access to Export operations on UserManagement integration pipelines",
                            Name = "UserManagement.Export"
                        },
                        new
                        {
                            Id = new Guid("62513fdc-dcdb-462d-955c-948a6c2adc26"),
                            Category = "UserManagement",
                            Description = "Limited scope for Import operations on UserManagement system resources",
                            Name = "UserManagement.Import"
                        },
                        new
                        {
                            Id = new Guid("23fb4d21-7501-40d8-8501-6e70989ecbda"),
                            Category = "UserManagement",
                            Description = "Delegated authority for Archive operations on UserManagement audit logs",
                            Name = "UserManagement.Archive"
                        },
                        new
                        {
                            Id = new Guid("2d5835a2-a82d-4577-b210-1c628d464cb1"),
                            Category = "UserManagement",
                            Description = "Global access to Restore operations on UserManagement API endpoints",
                            Name = "UserManagement.Restore"
                        },
                        new
                        {
                            Id = new Guid("8e5085b5-dfd3-4b13-98be-7073229a87fb"),
                            Category = "UserManagement",
                            Description = "Global access to Lock operations on UserManagement security policies",
                            Name = "UserManagement.Lock"
                        },
                        new
                        {
                            Id = new Guid("99fb2476-16ec-4443-91e4-1637dbf8c9fb"),
                            Category = "UserManagement",
                            Description = "Emergency access to Unlock operations on UserManagement user profiles",
                            Name = "UserManagement.Unlock"
                        },
                        new
                        {
                            Id = new Guid("1816758c-4cb5-49b5-8d3a-798090dbabb8"),
                            Category = "UserManagement",
                            Description = "Delegated authority for Grant operations on UserManagement security policies",
                            Name = "UserManagement.Grant"
                        },
                        new
                        {
                            Id = new Guid("4f9b655c-3ce7-4c6a-a5c5-d45505bbf0f0"),
                            Category = "UserManagement",
                            Description = "Global access to Revoke operations on UserManagement sensitive data",
                            Name = "UserManagement.Revoke"
                        },
                        new
                        {
                            Id = new Guid("5cefefcf-e127-4c92-85bb-0de671a1e300"),
                            Category = "UserManagement",
                            Description = "Compliance-related access to Execute operations on UserManagement system resources",
                            Name = "UserManagement.Execute"
                        },
                        new
                        {
                            Id = new Guid("a449c910-5dff-407e-87e9-ad2760197c22"),
                            Category = "UserManagement",
                            Description = "Compliance-related access to Schedule operations on UserManagement workflow definitions",
                            Name = "UserManagement.Schedule"
                        },
                        new
                        {
                            Id = new Guid("d63c4d58-bbb2-4a7a-b1b2-6010ce1f0c26"),
                            Category = "UserManagement",
                            Description = "Administrative control over Monitor operations on UserManagement integration pipelines",
                            Name = "UserManagement.Monitor"
                        },
                        new
                        {
                            Id = new Guid("f823ed4c-3bbe-488e-bfb5-a8f8843dae59"),
                            Category = "UserManagement",
                            Description = "Approval workflow covering Configure operations on UserManagement system resources",
                            Name = "UserManagement.Configure"
                        },
                        new
                        {
                            Id = new Guid("34010ea4-b4a7-4cbe-9213-f277a61a39a2"),
                            Category = "UserManagement",
                            Description = "Temporary permission to Bypass operations on UserManagement workflow definitions",
                            Name = "UserManagement.Bypass"
                        },
                        new
                        {
                            Id = new Guid("6f381b62-e013-4e0f-a793-24bbb0964926"),
                            Category = "UserManagement",
                            Description = "Emergency access to Delegate operations on UserManagement reporting modules",
                            Name = "UserManagement.Delegate"
                        },
                        new
                        {
                            Id = new Guid("1f51def2-0982-4d0a-9a15-28c9c94126aa"),
                            Category = "RoleManagement",
                            Description = "Audit capability for View operations on RoleManagement integration pipelines",
                            Name = "RoleManagement.View"
                        },
                        new
                        {
                            Id = new Guid("1d5ca28d-3172-472a-a4ce-9c94c20d3b71"),
                            Category = "RoleManagement",
                            Description = "Audit capability for Create operations on RoleManagement user profiles",
                            Name = "RoleManagement.Create"
                        },
                        new
                        {
                            Id = new Guid("12e26c5b-47b4-4d86-8407-1519c97313dc"),
                            Category = "RoleManagement",
                            Description = "Emergency access to Edit operations on RoleManagement user profiles",
                            Name = "RoleManagement.Edit"
                        },
                        new
                        {
                            Id = new Guid("3cef7bdd-b887-4aa9-b855-921c908a333f"),
                            Category = "RoleManagement",
                            Description = "Limited scope for Delete operations on RoleManagement integration pipelines",
                            Name = "RoleManagement.Delete"
                        },
                        new
                        {
                            Id = new Guid("6f5fe80b-2f68-4062-a521-1443403c6a93"),
                            Category = "RoleManagement",
                            Description = "Approval workflow covering Approve operations on RoleManagement configuration settings",
                            Name = "RoleManagement.Approve"
                        },
                        new
                        {
                            Id = new Guid("6d5b4088-5b77-4ffb-b764-cad05b7e140e"),
                            Category = "RoleManagement",
                            Description = "Administrative control over Reject operations on RoleManagement reporting modules",
                            Name = "RoleManagement.Reject"
                        },
                        new
                        {
                            Id = new Guid("9c404f19-74e0-45e0-aa75-9dcb3e3bffb3"),
                            Category = "RoleManagement",
                            Description = "Limited scope for Export operations on RoleManagement security policies",
                            Name = "RoleManagement.Export"
                        },
                        new
                        {
                            Id = new Guid("5e554e99-77bc-4875-b1c4-18c8c3910d1c"),
                            Category = "RoleManagement",
                            Description = "Audit capability for Import operations on RoleManagement configuration settings",
                            Name = "RoleManagement.Import"
                        },
                        new
                        {
                            Id = new Guid("14b1c343-d222-4dec-9968-bbc36cf1f0b5"),
                            Category = "RoleManagement",
                            Description = "Global access to Archive operations on RoleManagement user profiles",
                            Name = "RoleManagement.Archive"
                        },
                        new
                        {
                            Id = new Guid("7252137f-3853-4838-a41e-c29f69fdedce"),
                            Category = "RoleManagement",
                            Description = "Security-restricted Restore operations on RoleManagement configuration settings",
                            Name = "RoleManagement.Restore"
                        },
                        new
                        {
                            Id = new Guid("e8a57c3c-fd34-4af9-98b9-0b1480c87053"),
                            Category = "RoleManagement",
                            Description = "Global access to Lock operations on RoleManagement API endpoints",
                            Name = "RoleManagement.Lock"
                        },
                        new
                        {
                            Id = new Guid("dddc8c3c-c753-40df-a306-75c2f5c871e2"),
                            Category = "RoleManagement",
                            Description = "Limited scope for Unlock operations on RoleManagement user profiles",
                            Name = "RoleManagement.Unlock"
                        },
                        new
                        {
                            Id = new Guid("1e9f0884-ff3f-4dc4-b264-4d40722c601d"),
                            Category = "RoleManagement",
                            Description = "Security-restricted Grant operations on RoleManagement integration pipelines",
                            Name = "RoleManagement.Grant"
                        },
                        new
                        {
                            Id = new Guid("1c92b10a-7497-412a-9e79-10407e117bff"),
                            Category = "RoleManagement",
                            Description = "Compliance-related access to Revoke operations on RoleManagement sensitive data",
                            Name = "RoleManagement.Revoke"
                        },
                        new
                        {
                            Id = new Guid("2d99030c-27fa-41af-bc96-bcfca362d3ae"),
                            Category = "RoleManagement",
                            Description = "Security-restricted Execute operations on RoleManagement workflow definitions",
                            Name = "RoleManagement.Execute"
                        },
                        new
                        {
                            Id = new Guid("3d544a11-b9e4-49ea-bd9d-6fdbc58ea44a"),
                            Category = "RoleManagement",
                            Description = "Limited scope for Schedule operations on RoleManagement user profiles",
                            Name = "RoleManagement.Schedule"
                        },
                        new
                        {
                            Id = new Guid("5002893f-8eef-4034-889c-76b2eeadd690"),
                            Category = "RoleManagement",
                            Description = "Administrative control over Monitor operations on RoleManagement audit logs",
                            Name = "RoleManagement.Monitor"
                        },
                        new
                        {
                            Id = new Guid("dba0b7e0-8381-49de-9035-95e83cd487c8"),
                            Category = "RoleManagement",
                            Description = "Delegated authority for Configure operations on RoleManagement reporting modules",
                            Name = "RoleManagement.Configure"
                        },
                        new
                        {
                            Id = new Guid("9284d316-a67f-4493-b742-8f40ce2ac2bb"),
                            Category = "RoleManagement",
                            Description = "Compliance-related access to Bypass operations on RoleManagement reporting modules",
                            Name = "RoleManagement.Bypass"
                        },
                        new
                        {
                            Id = new Guid("30c87ecb-fc6f-4963-84e7-4a62e5adcf5a"),
                            Category = "RoleManagement",
                            Description = "Audit capability for Delegate operations on RoleManagement integration pipelines",
                            Name = "RoleManagement.Delegate"
                        },
                        new
                        {
                            Id = new Guid("b44b4e54-c7e4-4114-8e6e-69b52054e7fd"),
                            Category = "DataAccess",
                            Description = "Audit capability for View operations on DataAccess security policies",
                            Name = "DataAccess.View"
                        },
                        new
                        {
                            Id = new Guid("9828059a-1d28-4b75-b971-9329297c9632"),
                            Category = "DataAccess",
                            Description = "Emergency access to Create operations on DataAccess API endpoints",
                            Name = "DataAccess.Create"
                        },
                        new
                        {
                            Id = new Guid("0cbd47b8-e0ad-4978-b345-714a21118719"),
                            Category = "DataAccess",
                            Description = "Audit capability for Edit operations on DataAccess API endpoints",
                            Name = "DataAccess.Edit"
                        },
                        new
                        {
                            Id = new Guid("f189d1fd-e42d-4acc-9bd5-947b62accf2d"),
                            Category = "DataAccess",
                            Description = "Delegated authority for Delete operations on DataAccess integration pipelines",
                            Name = "DataAccess.Delete"
                        },
                        new
                        {
                            Id = new Guid("b67f4d57-9e77-4e2f-9404-ebe5b9c5e8f5"),
                            Category = "DataAccess",
                            Description = "Delegated authority for Approve operations on DataAccess API endpoints",
                            Name = "DataAccess.Approve"
                        },
                        new
                        {
                            Id = new Guid("983dadc9-7cb7-42cd-b291-75d84bec2d56"),
                            Category = "DataAccess",
                            Description = "Audit capability for Reject operations on DataAccess reporting modules",
                            Name = "DataAccess.Reject"
                        },
                        new
                        {
                            Id = new Guid("a44bcabb-dbf3-486c-b88c-c90a535c7199"),
                            Category = "DataAccess",
                            Description = "Delegated authority for Export operations on DataAccess sensitive data",
                            Name = "DataAccess.Export"
                        },
                        new
                        {
                            Id = new Guid("9a8c40c0-5c86-4f36-bf62-76a87e5bed91"),
                            Category = "DataAccess",
                            Description = "Emergency access to Import operations on DataAccess integration pipelines",
                            Name = "DataAccess.Import"
                        },
                        new
                        {
                            Id = new Guid("fc3881de-fcec-468b-bb10-4c572f13e52b"),
                            Category = "DataAccess",
                            Description = "Compliance-related access to Archive operations on DataAccess reporting modules",
                            Name = "DataAccess.Archive"
                        },
                        new
                        {
                            Id = new Guid("8a0c643e-4391-47f8-986a-496858ba4f2e"),
                            Category = "DataAccess",
                            Description = "Limited scope for Restore operations on DataAccess audit logs",
                            Name = "DataAccess.Restore"
                        },
                        new
                        {
                            Id = new Guid("b6ab0601-2f98-45f6-a038-b36eafb9c47d"),
                            Category = "DataAccess",
                            Description = "Emergency access to Lock operations on DataAccess reporting modules",
                            Name = "DataAccess.Lock"
                        },
                        new
                        {
                            Id = new Guid("3e390c37-263d-41a0-ad31-c337b2e5edbe"),
                            Category = "DataAccess",
                            Description = "Security-restricted Unlock operations on DataAccess user profiles",
                            Name = "DataAccess.Unlock"
                        },
                        new
                        {
                            Id = new Guid("7115dcd0-61c2-4cb2-ab72-3f96e8d71686"),
                            Category = "DataAccess",
                            Description = "Compliance-related access to Grant operations on DataAccess API endpoints",
                            Name = "DataAccess.Grant"
                        },
                        new
                        {
                            Id = new Guid("92533291-0563-4627-b8e8-cdab7055433b"),
                            Category = "DataAccess",
                            Description = "Compliance-related access to Revoke operations on DataAccess sensitive data",
                            Name = "DataAccess.Revoke"
                        },
                        new
                        {
                            Id = new Guid("07e37905-6a91-4f67-bac9-d78286f63d4a"),
                            Category = "DataAccess",
                            Description = "Temporary permission to Execute operations on DataAccess sensitive data",
                            Name = "DataAccess.Execute"
                        },
                        new
                        {
                            Id = new Guid("6b8dc4ae-588d-4738-afeb-38f17327cb29"),
                            Category = "DataAccess",
                            Description = "Global access to Schedule operations on DataAccess configuration settings",
                            Name = "DataAccess.Schedule"
                        },
                        new
                        {
                            Id = new Guid("75e2bf09-b39c-4445-b46f-21953b9e2f05"),
                            Category = "DataAccess",
                            Description = "Delegated authority for Monitor operations on DataAccess audit logs",
                            Name = "DataAccess.Monitor"
                        },
                        new
                        {
                            Id = new Guid("3b3059db-3510-4c80-8dd8-400a29b9e17a"),
                            Category = "DataAccess",
                            Description = "Temporary permission to Configure operations on DataAccess integration pipelines",
                            Name = "DataAccess.Configure"
                        },
                        new
                        {
                            Id = new Guid("b9f4b711-f933-4fa0-a5cb-4b0c68718117"),
                            Category = "DataAccess",
                            Description = "Audit capability for Bypass operations on DataAccess configuration settings",
                            Name = "DataAccess.Bypass"
                        },
                        new
                        {
                            Id = new Guid("7a943dfb-929c-45be-b793-6029492d6871"),
                            Category = "DataAccess",
                            Description = "Emergency access to Delegate operations on DataAccess sensitive data",
                            Name = "DataAccess.Delegate"
                        },
                        new
                        {
                            Id = new Guid("37c2d20a-2713-4a51-a9b0-0630975b7624"),
                            Category = "Reporting",
                            Description = "Approval workflow covering View operations on Reporting audit logs",
                            Name = "Reporting.View"
                        },
                        new
                        {
                            Id = new Guid("a4deeb5a-4400-4add-9a63-c0f968b5db3d"),
                            Category = "Reporting",
                            Description = "Temporary permission to Create operations on Reporting workflow definitions",
                            Name = "Reporting.Create"
                        },
                        new
                        {
                            Id = new Guid("e62e4f0e-e6c4-4bd1-8909-3e2b9840ac85"),
                            Category = "Reporting",
                            Description = "Administrative control over Edit operations on Reporting workflow definitions",
                            Name = "Reporting.Edit"
                        },
                        new
                        {
                            Id = new Guid("3ea4332c-957f-4902-8960-7cac92c25ac3"),
                            Category = "Reporting",
                            Description = "Administrative control over Delete operations on Reporting user profiles",
                            Name = "Reporting.Delete"
                        },
                        new
                        {
                            Id = new Guid("8519edb5-2511-4896-947c-6e9248dad40e"),
                            Category = "Reporting",
                            Description = "Audit capability for Approve operations on Reporting configuration settings",
                            Name = "Reporting.Approve"
                        },
                        new
                        {
                            Id = new Guid("1345bab8-7d18-451a-844b-1c7d84ba84c9"),
                            Category = "Reporting",
                            Description = "Delegated authority for Reject operations on Reporting workflow definitions",
                            Name = "Reporting.Reject"
                        },
                        new
                        {
                            Id = new Guid("4d65025c-7adb-491b-8053-d911eb1c353a"),
                            Category = "Reporting",
                            Description = "Compliance-related access to Export operations on Reporting audit logs",
                            Name = "Reporting.Export"
                        },
                        new
                        {
                            Id = new Guid("47bd7054-c630-4e1b-a580-725d1a77069a"),
                            Category = "Reporting",
                            Description = "Approval workflow covering Import operations on Reporting user profiles",
                            Name = "Reporting.Import"
                        },
                        new
                        {
                            Id = new Guid("6540fc85-ade9-4201-8bc4-10861d594b65"),
                            Category = "Reporting",
                            Description = "Emergency access to Archive operations on Reporting configuration settings",
                            Name = "Reporting.Archive"
                        },
                        new
                        {
                            Id = new Guid("4c8d6b08-e95e-405b-b5ce-49f5d805034a"),
                            Category = "Reporting",
                            Description = "Limited scope for Restore operations on Reporting workflow definitions",
                            Name = "Reporting.Restore"
                        },
                        new
                        {
                            Id = new Guid("00926377-e008-44e0-b170-9d413b34a72c"),
                            Category = "Reporting",
                            Description = "Limited scope for Lock operations on Reporting configuration settings",
                            Name = "Reporting.Lock"
                        },
                        new
                        {
                            Id = new Guid("00b32205-fd18-4916-925e-1c2dbb3e888b"),
                            Category = "Reporting",
                            Description = "Security-restricted Unlock operations on Reporting workflow definitions",
                            Name = "Reporting.Unlock"
                        },
                        new
                        {
                            Id = new Guid("3a33432d-4886-4908-ac0b-aec7354c06b6"),
                            Category = "Reporting",
                            Description = "Approval workflow covering Grant operations on Reporting integration pipelines",
                            Name = "Reporting.Grant"
                        },
                        new
                        {
                            Id = new Guid("008542dd-0678-42d1-a5b4-296d411fb3cb"),
                            Category = "Reporting",
                            Description = "Audit capability for Revoke operations on Reporting user profiles",
                            Name = "Reporting.Revoke"
                        },
                        new
                        {
                            Id = new Guid("0ce6bb6a-c7d2-4072-a344-464ef8ea9120"),
                            Category = "Reporting",
                            Description = "Administrative control over Execute operations on Reporting security policies",
                            Name = "Reporting.Execute"
                        },
                        new
                        {
                            Id = new Guid("0767faa4-cb31-4300-b1db-56ffc3c91f8a"),
                            Category = "Reporting",
                            Description = "Global access to Schedule operations on Reporting reporting modules",
                            Name = "Reporting.Schedule"
                        },
                        new
                        {
                            Id = new Guid("e97a3591-b768-445e-b0ba-7caa53220e34"),
                            Category = "Reporting",
                            Description = "Security-restricted Monitor operations on Reporting configuration settings",
                            Name = "Reporting.Monitor"
                        },
                        new
                        {
                            Id = new Guid("2e0b8e78-c8a8-42a7-959b-05cff7c49826"),
                            Category = "Reporting",
                            Description = "Audit capability for Configure operations on Reporting system resources",
                            Name = "Reporting.Configure"
                        },
                        new
                        {
                            Id = new Guid("0b5573c9-a4bd-427e-9a6d-fdabd2fd95cc"),
                            Category = "Reporting",
                            Description = "Limited scope for Bypass operations on Reporting integration pipelines",
                            Name = "Reporting.Bypass"
                        },
                        new
                        {
                            Id = new Guid("7f0cebc3-c82f-45f2-b348-00af42bb6b5d"),
                            Category = "Reporting",
                            Description = "Audit capability for Delegate operations on Reporting API endpoints",
                            Name = "Reporting.Delegate"
                        },
                        new
                        {
                            Id = new Guid("20e98afc-b6b0-4c27-b416-ce8de2995c38"),
                            Category = "SystemConfig",
                            Description = "Compliance-related access to View operations on SystemConfig audit logs",
                            Name = "SystemConfig.View"
                        },
                        new
                        {
                            Id = new Guid("4b7f1e0c-7210-4719-a84d-447ca9629b35"),
                            Category = "SystemConfig",
                            Description = "Emergency access to Create operations on SystemConfig system resources",
                            Name = "SystemConfig.Create"
                        },
                        new
                        {
                            Id = new Guid("5f91284d-12c5-4004-bb05-d9daefcf7281"),
                            Category = "SystemConfig",
                            Description = "Global access to Edit operations on SystemConfig API endpoints",
                            Name = "SystemConfig.Edit"
                        },
                        new
                        {
                            Id = new Guid("98f6e267-6d16-43dc-a2dc-bbe14f954f1e"),
                            Category = "SystemConfig",
                            Description = "Audit capability for Delete operations on SystemConfig security policies",
                            Name = "SystemConfig.Delete"
                        },
                        new
                        {
                            Id = new Guid("564ae470-3bc0-4b7f-a2ed-162f4c7dd395"),
                            Category = "SystemConfig",
                            Description = "Emergency access to Approve operations on SystemConfig system resources",
                            Name = "SystemConfig.Approve"
                        },
                        new
                        {
                            Id = new Guid("1006f736-a698-4644-aad4-02668bf75534"),
                            Category = "SystemConfig",
                            Description = "Approval workflow covering Reject operations on SystemConfig audit logs",
                            Name = "SystemConfig.Reject"
                        },
                        new
                        {
                            Id = new Guid("76298891-74bf-4da8-b0fb-4dc094afc0c9"),
                            Category = "SystemConfig",
                            Description = "Audit capability for Export operations on SystemConfig integration pipelines",
                            Name = "SystemConfig.Export"
                        },
                        new
                        {
                            Id = new Guid("510eb298-2d47-46fb-9722-abe098f341bf"),
                            Category = "SystemConfig",
                            Description = "Temporary permission to Import operations on SystemConfig API endpoints",
                            Name = "SystemConfig.Import"
                        },
                        new
                        {
                            Id = new Guid("df0b4f31-c682-4459-affb-0fc2e07145fb"),
                            Category = "SystemConfig",
                            Description = "Approval workflow covering Archive operations on SystemConfig configuration settings",
                            Name = "SystemConfig.Archive"
                        },
                        new
                        {
                            Id = new Guid("f7ca4a3d-350b-4cca-a7dd-81497b6386b8"),
                            Category = "SystemConfig",
                            Description = "Emergency access to Restore operations on SystemConfig API endpoints",
                            Name = "SystemConfig.Restore"
                        },
                        new
                        {
                            Id = new Guid("94cd965c-d28e-40c9-8686-2f11b5c00343"),
                            Category = "SystemConfig",
                            Description = "Compliance-related access to Lock operations on SystemConfig system resources",
                            Name = "SystemConfig.Lock"
                        },
                        new
                        {
                            Id = new Guid("7917af91-0abf-49cb-bf78-80ec609a4d30"),
                            Category = "SystemConfig",
                            Description = "Delegated authority for Unlock operations on SystemConfig workflow definitions",
                            Name = "SystemConfig.Unlock"
                        },
                        new
                        {
                            Id = new Guid("8750bd52-577f-4600-ac90-329b962ee4d5"),
                            Category = "SystemConfig",
                            Description = "Delegated authority for Grant operations on SystemConfig system resources",
                            Name = "SystemConfig.Grant"
                        },
                        new
                        {
                            Id = new Guid("27d7fb0f-cef5-42f2-b364-95dd8e90a567"),
                            Category = "SystemConfig",
                            Description = "Administrative control over Revoke operations on SystemConfig API endpoints",
                            Name = "SystemConfig.Revoke"
                        },
                        new
                        {
                            Id = new Guid("3251e45c-8fca-4ad7-bb2e-37e801bd4f8b"),
                            Category = "SystemConfig",
                            Description = "Compliance-related access to Execute operations on SystemConfig system resources",
                            Name = "SystemConfig.Execute"
                        },
                        new
                        {
                            Id = new Guid("eedfdd19-1205-4e99-9dca-b9cb48434529"),
                            Category = "SystemConfig",
                            Description = "Administrative control over Schedule operations on SystemConfig user profiles",
                            Name = "SystemConfig.Schedule"
                        },
                        new
                        {
                            Id = new Guid("993a3b78-b5a7-4e0c-aee4-1441d3d9192a"),
                            Category = "SystemConfig",
                            Description = "Administrative control over Monitor operations on SystemConfig integration pipelines",
                            Name = "SystemConfig.Monitor"
                        },
                        new
                        {
                            Id = new Guid("dfaefdd1-4243-4bd0-82d3-92ee12071bd3"),
                            Category = "SystemConfig",
                            Description = "Approval workflow covering Configure operations on SystemConfig security policies",
                            Name = "SystemConfig.Configure"
                        },
                        new
                        {
                            Id = new Guid("40e2a1e3-7238-4f9c-a236-e13623ab3099"),
                            Category = "SystemConfig",
                            Description = "Delegated authority for Bypass operations on SystemConfig user profiles",
                            Name = "SystemConfig.Bypass"
                        },
                        new
                        {
                            Id = new Guid("b4e6cba9-3906-4deb-885b-310ae3422246"),
                            Category = "SystemConfig",
                            Description = "Administrative control over Delegate operations on SystemConfig workflow definitions",
                            Name = "SystemConfig.Delegate"
                        },
                        new
                        {
                            Id = new Guid("19b04961-1eb1-4bd0-aa65-992d079cd21e"),
                            Category = "Workflow",
                            Description = "Compliance-related access to View operations on Workflow audit logs",
                            Name = "Workflow.View"
                        },
                        new
                        {
                            Id = new Guid("2ca9d773-4203-454b-bcef-27db593280c7"),
                            Category = "Workflow",
                            Description = "Security-restricted Create operations on Workflow system resources",
                            Name = "Workflow.Create"
                        },
                        new
                        {
                            Id = new Guid("699b7769-6226-410f-b676-cdfa3560cd78"),
                            Category = "Workflow",
                            Description = "Security-restricted Edit operations on Workflow security policies",
                            Name = "Workflow.Edit"
                        },
                        new
                        {
                            Id = new Guid("639b4636-e7c5-4597-b9b2-aa17d60ba98b"),
                            Category = "Workflow",
                            Description = "Approval workflow covering Delete operations on Workflow sensitive data",
                            Name = "Workflow.Delete"
                        },
                        new
                        {
                            Id = new Guid("f329dce1-7b04-46ad-9061-2b8a035e3eef"),
                            Category = "Workflow",
                            Description = "Delegated authority for Approve operations on Workflow configuration settings",
                            Name = "Workflow.Approve"
                        },
                        new
                        {
                            Id = new Guid("9a9a7fbb-2e8d-4691-b7f8-ee584be7b4e2"),
                            Category = "Workflow",
                            Description = "Audit capability for Reject operations on Workflow integration pipelines",
                            Name = "Workflow.Reject"
                        },
                        new
                        {
                            Id = new Guid("4dec20e1-8455-4512-862a-982bcaf1a07e"),
                            Category = "Workflow",
                            Description = "Compliance-related access to Export operations on Workflow system resources",
                            Name = "Workflow.Export"
                        },
                        new
                        {
                            Id = new Guid("af4def4f-05a3-4afb-b8ee-cafe01b64ac5"),
                            Category = "Workflow",
                            Description = "Delegated authority for Import operations on Workflow API endpoints",
                            Name = "Workflow.Import"
                        },
                        new
                        {
                            Id = new Guid("8726ef8a-22d4-40e3-960c-dfd2f16a9a6c"),
                            Category = "Workflow",
                            Description = "Audit capability for Archive operations on Workflow configuration settings",
                            Name = "Workflow.Archive"
                        },
                        new
                        {
                            Id = new Guid("2470b065-aac5-4100-b19a-6fbbcddc8ce1"),
                            Category = "Workflow",
                            Description = "Temporary permission to Restore operations on Workflow sensitive data",
                            Name = "Workflow.Restore"
                        },
                        new
                        {
                            Id = new Guid("3a0cb33e-8723-4493-bc13-ea1f5be9ad60"),
                            Category = "Workflow",
                            Description = "Administrative control over Lock operations on Workflow API endpoints",
                            Name = "Workflow.Lock"
                        },
                        new
                        {
                            Id = new Guid("ea889b3c-b219-4895-9aa8-b13c3ad111aa"),
                            Category = "Workflow",
                            Description = "Global access to Unlock operations on Workflow workflow definitions",
                            Name = "Workflow.Unlock"
                        },
                        new
                        {
                            Id = new Guid("2c9c22c0-a62f-4889-99fc-b246a62a9ecf"),
                            Category = "Workflow",
                            Description = "Audit capability for Grant operations on Workflow API endpoints",
                            Name = "Workflow.Grant"
                        },
                        new
                        {
                            Id = new Guid("e99cabea-3566-4540-89c2-9a89fb208fec"),
                            Category = "Workflow",
                            Description = "Security-restricted Revoke operations on Workflow workflow definitions",
                            Name = "Workflow.Revoke"
                        },
                        new
                        {
                            Id = new Guid("f7977b71-ec00-4ee9-af8c-87500cba2d23"),
                            Category = "Workflow",
                            Description = "Limited scope for Execute operations on Workflow sensitive data",
                            Name = "Workflow.Execute"
                        },
                        new
                        {
                            Id = new Guid("d11d4874-d312-4b4f-aaa2-1097e06e0504"),
                            Category = "Workflow",
                            Description = "Temporary permission to Schedule operations on Workflow API endpoints",
                            Name = "Workflow.Schedule"
                        },
                        new
                        {
                            Id = new Guid("ea0eded9-18a1-4987-8282-0d1d9980b647"),
                            Category = "Workflow",
                            Description = "Limited scope for Monitor operations on Workflow integration pipelines",
                            Name = "Workflow.Monitor"
                        },
                        new
                        {
                            Id = new Guid("407b035a-31bb-4e63-b94e-a759c069e5e1"),
                            Category = "Workflow",
                            Description = "Emergency access to Configure operations on Workflow configuration settings",
                            Name = "Workflow.Configure"
                        },
                        new
                        {
                            Id = new Guid("53ca7ec8-bbed-4f51-aeeb-7a2f8e451398"),
                            Category = "Workflow",
                            Description = "Security-restricted Bypass operations on Workflow system resources",
                            Name = "Workflow.Bypass"
                        },
                        new
                        {
                            Id = new Guid("e7b276d3-ccd4-4ed6-ba47-5397469246bd"),
                            Category = "Workflow",
                            Description = "Limited scope for Delegate operations on Workflow audit logs",
                            Name = "Workflow.Delegate"
                        },
                        new
                        {
                            Id = new Guid("d3636e24-e31a-44a8-a9b4-6afdc7965518"),
                            Category = "API",
                            Description = "Emergency access to View operations on API user profiles",
                            Name = "API.View"
                        },
                        new
                        {
                            Id = new Guid("b2dfbf2c-e2f0-4bf1-ab0c-4663bd43f04d"),
                            Category = "API",
                            Description = "Emergency access to Create operations on API reporting modules",
                            Name = "API.Create"
                        },
                        new
                        {
                            Id = new Guid("024a5e59-f9c1-4154-949b-eedb6888d406"),
                            Category = "API",
                            Description = "Administrative control over Edit operations on API security policies",
                            Name = "API.Edit"
                        },
                        new
                        {
                            Id = new Guid("7d768196-701b-4f98-b2b7-09b6c4d032c3"),
                            Category = "API",
                            Description = "Security-restricted Delete operations on API API endpoints",
                            Name = "API.Delete"
                        },
                        new
                        {
                            Id = new Guid("fa3a550b-c27f-45d7-9d5c-1b65c8687e24"),
                            Category = "API",
                            Description = "Temporary permission to Approve operations on API audit logs",
                            Name = "API.Approve"
                        },
                        new
                        {
                            Id = new Guid("08d6cd29-12db-4307-b444-f8c816d10d0b"),
                            Category = "API",
                            Description = "Compliance-related access to Reject operations on API user profiles",
                            Name = "API.Reject"
                        },
                        new
                        {
                            Id = new Guid("8f0f2d2b-8232-4805-b437-b892a1c21b87"),
                            Category = "API",
                            Description = "Delegated authority for Export operations on API configuration settings",
                            Name = "API.Export"
                        },
                        new
                        {
                            Id = new Guid("ad7e1621-151d-47f3-b456-da87fab0f4cd"),
                            Category = "API",
                            Description = "Security-restricted Import operations on API configuration settings",
                            Name = "API.Import"
                        },
                        new
                        {
                            Id = new Guid("50a91a80-530b-4c62-a628-c4f5d86ede8f"),
                            Category = "API",
                            Description = "Compliance-related access to Archive operations on API reporting modules",
                            Name = "API.Archive"
                        },
                        new
                        {
                            Id = new Guid("99a9fbe2-6942-4270-9a92-cec50cd453ab"),
                            Category = "API",
                            Description = "Global access to Restore operations on API audit logs",
                            Name = "API.Restore"
                        },
                        new
                        {
                            Id = new Guid("a1526f4b-7913-4beb-8d81-b3eac2828aa0"),
                            Category = "API",
                            Description = "Audit capability for Lock operations on API workflow definitions",
                            Name = "API.Lock"
                        },
                        new
                        {
                            Id = new Guid("756caefd-9ab5-43c6-80e6-b1b680bf3fe5"),
                            Category = "API",
                            Description = "Global access to Unlock operations on API sensitive data",
                            Name = "API.Unlock"
                        },
                        new
                        {
                            Id = new Guid("0fc3bdc8-b731-4337-9c8d-fa6ccbe2c02a"),
                            Category = "API",
                            Description = "Limited scope for Grant operations on API integration pipelines",
                            Name = "API.Grant"
                        },
                        new
                        {
                            Id = new Guid("bac52c29-09a1-4ade-aad1-88ba8237929a"),
                            Category = "API",
                            Description = "Emergency access to Revoke operations on API configuration settings",
                            Name = "API.Revoke"
                        },
                        new
                        {
                            Id = new Guid("dd8172c6-cf10-426d-b85a-cc60a2a3164a"),
                            Category = "API",
                            Description = "Compliance-related access to Execute operations on API security policies",
                            Name = "API.Execute"
                        },
                        new
                        {
                            Id = new Guid("24d49659-0716-419d-bbc3-5131caa800b1"),
                            Category = "API",
                            Description = "Temporary permission to Schedule operations on API audit logs",
                            Name = "API.Schedule"
                        },
                        new
                        {
                            Id = new Guid("0b4ee39f-d63d-4b64-a105-7cd71b13c9d0"),
                            Category = "API",
                            Description = "Limited scope for Monitor operations on API security policies",
                            Name = "API.Monitor"
                        },
                        new
                        {
                            Id = new Guid("67b079a8-9c7a-4994-86b5-b7ce96ae2ae5"),
                            Category = "API",
                            Description = "Temporary permission to Configure operations on API security policies",
                            Name = "API.Configure"
                        },
                        new
                        {
                            Id = new Guid("7574b4ec-a344-4c14-8304-9f2a5722d8b1"),
                            Category = "API",
                            Description = "Emergency access to Bypass operations on API workflow definitions",
                            Name = "API.Bypass"
                        },
                        new
                        {
                            Id = new Guid("7ae311fa-0899-4c45-a7c2-0a86520b631f"),
                            Category = "API",
                            Description = "Delegated authority for Delegate operations on API reporting modules",
                            Name = "API.Delegate"
                        },
                        new
                        {
                            Id = new Guid("39ce3d6a-1927-47b3-aee6-92051113330b"),
                            Category = "Integration",
                            Description = "Temporary permission to View operations on Integration API endpoints",
                            Name = "Integration.View"
                        },
                        new
                        {
                            Id = new Guid("089bd578-93ad-4dac-8fe1-6e7b67d7223d"),
                            Category = "Integration",
                            Description = "Emergency access to Create operations on Integration security policies",
                            Name = "Integration.Create"
                        },
                        new
                        {
                            Id = new Guid("89577654-1e6e-4ca7-a6c9-d6f101b5bd6a"),
                            Category = "Integration",
                            Description = "Delegated authority for Edit operations on Integration security policies",
                            Name = "Integration.Edit"
                        },
                        new
                        {
                            Id = new Guid("2d4d06e2-89b4-4529-a282-8e20de9b1163"),
                            Category = "Integration",
                            Description = "Delegated authority for Delete operations on Integration configuration settings",
                            Name = "Integration.Delete"
                        },
                        new
                        {
                            Id = new Guid("409f293f-bac7-43a3-8416-30f7739491a2"),
                            Category = "Integration",
                            Description = "Approval workflow covering Approve operations on Integration user profiles",
                            Name = "Integration.Approve"
                        },
                        new
                        {
                            Id = new Guid("13b0cfc3-73fc-418d-95f3-1c7dd95ad34d"),
                            Category = "Integration",
                            Description = "Temporary permission to Reject operations on Integration system resources",
                            Name = "Integration.Reject"
                        },
                        new
                        {
                            Id = new Guid("d04ecf24-7c01-4ed3-80f4-6f3e74001202"),
                            Category = "Integration",
                            Description = "Administrative control over Export operations on Integration configuration settings",
                            Name = "Integration.Export"
                        },
                        new
                        {
                            Id = new Guid("2222821d-02d6-4755-bb94-a3781b652090"),
                            Category = "Integration",
                            Description = "Emergency access to Import operations on Integration audit logs",
                            Name = "Integration.Import"
                        },
                        new
                        {
                            Id = new Guid("9b793dd6-7618-4c1a-ba2a-4109cef629c9"),
                            Category = "Integration",
                            Description = "Delegated authority for Archive operations on Integration integration pipelines",
                            Name = "Integration.Archive"
                        },
                        new
                        {
                            Id = new Guid("10517cf6-b644-4e78-8973-b449866fd84a"),
                            Category = "Integration",
                            Description = "Temporary permission to Restore operations on Integration reporting modules",
                            Name = "Integration.Restore"
                        },
                        new
                        {
                            Id = new Guid("c37f3bf2-bac3-4c13-b255-b368c08d9b08"),
                            Category = "Integration",
                            Description = "Delegated authority for Lock operations on Integration sensitive data",
                            Name = "Integration.Lock"
                        },
                        new
                        {
                            Id = new Guid("5ee5645b-e65f-45f6-885a-53c43df22606"),
                            Category = "Integration",
                            Description = "Compliance-related access to Unlock operations on Integration API endpoints",
                            Name = "Integration.Unlock"
                        },
                        new
                        {
                            Id = new Guid("70a9d9d9-6cb1-487a-a7f8-de47c8918125"),
                            Category = "Integration",
                            Description = "Compliance-related access to Grant operations on Integration user profiles",
                            Name = "Integration.Grant"
                        },
                        new
                        {
                            Id = new Guid("b78da9cd-f66c-472b-b7a0-125951415609"),
                            Category = "Integration",
                            Description = "Security-restricted Revoke operations on Integration workflow definitions",
                            Name = "Integration.Revoke"
                        },
                        new
                        {
                            Id = new Guid("4929e663-831b-4058-92d9-00a7cbd53241"),
                            Category = "Integration",
                            Description = "Compliance-related access to Execute operations on Integration security policies",
                            Name = "Integration.Execute"
                        },
                        new
                        {
                            Id = new Guid("0161cbc9-1821-409e-a4f7-e09a0744905b"),
                            Category = "Integration",
                            Description = "Compliance-related access to Schedule operations on Integration API endpoints",
                            Name = "Integration.Schedule"
                        },
                        new
                        {
                            Id = new Guid("3b7cc10b-efb4-42b9-ba54-e2b373ae6ea6"),
                            Category = "Integration",
                            Description = "Emergency access to Monitor operations on Integration API endpoints",
                            Name = "Integration.Monitor"
                        },
                        new
                        {
                            Id = new Guid("afbaad3d-2372-43a6-a12f-e204acfe39ed"),
                            Category = "Integration",
                            Description = "Delegated authority for Configure operations on Integration reporting modules",
                            Name = "Integration.Configure"
                        },
                        new
                        {
                            Id = new Guid("4eb219a5-04ac-4142-85c7-51c3a8461184"),
                            Category = "Integration",
                            Description = "Approval workflow covering Bypass operations on Integration security policies",
                            Name = "Integration.Bypass"
                        },
                        new
                        {
                            Id = new Guid("2c29966a-8435-4d3f-ad2b-4fbbd46ae931"),
                            Category = "Integration",
                            Description = "Administrative control over Delegate operations on Integration integration pipelines",
                            Name = "Integration.Delegate"
                        },
                        new
                        {
                            Id = new Guid("d16c0bf6-56b6-46e0-822c-d4475bffc83b"),
                            Category = "Security",
                            Description = "Delegated authority for View operations on Security system resources",
                            Name = "Security.View"
                        },
                        new
                        {
                            Id = new Guid("02385c80-7f3d-4f86-b338-de6e4e14834d"),
                            Category = "Security",
                            Description = "Temporary permission to Create operations on Security security policies",
                            Name = "Security.Create"
                        },
                        new
                        {
                            Id = new Guid("25eab17c-18ad-4235-bf9e-2087d5eeeaf4"),
                            Category = "Security",
                            Description = "Limited scope for Edit operations on Security system resources",
                            Name = "Security.Edit"
                        },
                        new
                        {
                            Id = new Guid("6d99a15e-35fb-434a-b93c-76dd3c4079b2"),
                            Category = "Security",
                            Description = "Audit capability for Delete operations on Security configuration settings",
                            Name = "Security.Delete"
                        },
                        new
                        {
                            Id = new Guid("fc4d5c35-570f-417b-8d4d-ae11b038e630"),
                            Category = "Security",
                            Description = "Approval workflow covering Approve operations on Security security policies",
                            Name = "Security.Approve"
                        },
                        new
                        {
                            Id = new Guid("1dd7b85d-77d3-43ae-b992-a5f635dec756"),
                            Category = "Security",
                            Description = "Audit capability for Reject operations on Security user profiles",
                            Name = "Security.Reject"
                        },
                        new
                        {
                            Id = new Guid("7eeb765b-349c-4bde-bd17-0669903e365a"),
                            Category = "Security",
                            Description = "Administrative control over Export operations on Security sensitive data",
                            Name = "Security.Export"
                        },
                        new
                        {
                            Id = new Guid("3126aee7-5fe3-4267-8e59-7428d2ad3e90"),
                            Category = "Security",
                            Description = "Temporary permission to Import operations on Security API endpoints",
                            Name = "Security.Import"
                        },
                        new
                        {
                            Id = new Guid("c03b840d-7755-42cf-80b2-b5aefe37b629"),
                            Category = "Security",
                            Description = "Audit capability for Archive operations on Security audit logs",
                            Name = "Security.Archive"
                        },
                        new
                        {
                            Id = new Guid("ae6b4016-a09f-435a-84ca-b36319764e35"),
                            Category = "Security",
                            Description = "Global access to Restore operations on Security user profiles",
                            Name = "Security.Restore"
                        },
                        new
                        {
                            Id = new Guid("8ee7b0f8-8065-4cdc-87ce-592797d8ce18"),
                            Category = "Security",
                            Description = "Limited scope for Lock operations on Security reporting modules",
                            Name = "Security.Lock"
                        },
                        new
                        {
                            Id = new Guid("748016b4-a474-417d-abc3-5344a872592f"),
                            Category = "Security",
                            Description = "Audit capability for Unlock operations on Security configuration settings",
                            Name = "Security.Unlock"
                        },
                        new
                        {
                            Id = new Guid("cfaf14ee-b488-4ff4-8646-4fdfd4b63214"),
                            Category = "Security",
                            Description = "Approval workflow covering Grant operations on Security reporting modules",
                            Name = "Security.Grant"
                        },
                        new
                        {
                            Id = new Guid("3c73804c-9b51-44e9-bc08-b77fbac3ff0d"),
                            Category = "Security",
                            Description = "Approval workflow covering Revoke operations on Security user profiles",
                            Name = "Security.Revoke"
                        },
                        new
                        {
                            Id = new Guid("2f6d036d-ea06-41a8-9f5c-2315d84dd1a6"),
                            Category = "Security",
                            Description = "Administrative control over Execute operations on Security configuration settings",
                            Name = "Security.Execute"
                        },
                        new
                        {
                            Id = new Guid("347f0a56-b2eb-47a3-a622-0b050caffaa3"),
                            Category = "Security",
                            Description = "Compliance-related access to Schedule operations on Security API endpoints",
                            Name = "Security.Schedule"
                        },
                        new
                        {
                            Id = new Guid("c7da43ad-d651-46e6-8077-72eb03d6b273"),
                            Category = "Security",
                            Description = "Audit capability for Monitor operations on Security reporting modules",
                            Name = "Security.Monitor"
                        },
                        new
                        {
                            Id = new Guid("def400af-466c-491a-9fd1-3411211dabb1"),
                            Category = "Security",
                            Description = "Emergency access to Configure operations on Security reporting modules",
                            Name = "Security.Configure"
                        },
                        new
                        {
                            Id = new Guid("4d2c9387-0207-4b2b-8d70-dcdb060ddfa0"),
                            Category = "Security",
                            Description = "Delegated authority for Bypass operations on Security configuration settings",
                            Name = "Security.Bypass"
                        },
                        new
                        {
                            Id = new Guid("87531e04-e5dd-42cb-8b3d-5cfe488fafc1"),
                            Category = "Security",
                            Description = "Audit capability for Delegate operations on Security integration pipelines",
                            Name = "Security.Delegate"
                        },
                        new
                        {
                            Id = new Guid("fa6aa3a5-fb4f-4c60-8a8f-d48f221de6ec"),
                            Category = "Audit",
                            Description = "Limited scope for View operations on Audit sensitive data",
                            Name = "Audit.View"
                        },
                        new
                        {
                            Id = new Guid("fae30053-6a27-43c6-8872-814555bf8df9"),
                            Category = "Audit",
                            Description = "Approval workflow covering Create operations on Audit workflow definitions",
                            Name = "Audit.Create"
                        },
                        new
                        {
                            Id = new Guid("73083cd1-9c48-4e24-95cd-6171be18fad6"),
                            Category = "Audit",
                            Description = "Security-restricted Edit operations on Audit audit logs",
                            Name = "Audit.Edit"
                        },
                        new
                        {
                            Id = new Guid("2335fb33-d2e9-48ca-86ac-44c6a550f8b4"),
                            Category = "Audit",
                            Description = "Global access to Delete operations on Audit configuration settings",
                            Name = "Audit.Delete"
                        },
                        new
                        {
                            Id = new Guid("fdbb6b0e-57d8-4e47-905a-4b4825b6675b"),
                            Category = "Audit",
                            Description = "Security-restricted Approve operations on Audit audit logs",
                            Name = "Audit.Approve"
                        },
                        new
                        {
                            Id = new Guid("02423287-f75a-4bdb-84ce-fbaf5744efd8"),
                            Category = "Audit",
                            Description = "Security-restricted Reject operations on Audit sensitive data",
                            Name = "Audit.Reject"
                        },
                        new
                        {
                            Id = new Guid("47900bd0-44f1-4167-8542-81dc28f820eb"),
                            Category = "Audit",
                            Description = "Limited scope for Export operations on Audit system resources",
                            Name = "Audit.Export"
                        },
                        new
                        {
                            Id = new Guid("e0f684c6-8c1d-462e-9eac-945c9eb927aa"),
                            Category = "Audit",
                            Description = "Security-restricted Import operations on Audit workflow definitions",
                            Name = "Audit.Import"
                        },
                        new
                        {
                            Id = new Guid("1b6cb8e3-3a48-4502-a0c6-e7b5795dbaf2"),
                            Category = "Audit",
                            Description = "Delegated authority for Archive operations on Audit workflow definitions",
                            Name = "Audit.Archive"
                        },
                        new
                        {
                            Id = new Guid("b81ff648-0583-4488-bda4-11d6f1f6b692"),
                            Category = "Audit",
                            Description = "Temporary permission to Restore operations on Audit sensitive data",
                            Name = "Audit.Restore"
                        },
                        new
                        {
                            Id = new Guid("6f5c10fe-c3ca-47b2-bba2-79fc338c2624"),
                            Category = "Audit",
                            Description = "Security-restricted Lock operations on Audit security policies",
                            Name = "Audit.Lock"
                        },
                        new
                        {
                            Id = new Guid("31c2ef4f-1989-4a96-b237-cbde8ba55485"),
                            Category = "Audit",
                            Description = "Audit capability for Unlock operations on Audit reporting modules",
                            Name = "Audit.Unlock"
                        },
                        new
                        {
                            Id = new Guid("35ca9929-9912-4c50-a947-bd77303706b9"),
                            Category = "Audit",
                            Description = "Temporary permission to Grant operations on Audit integration pipelines",
                            Name = "Audit.Grant"
                        },
                        new
                        {
                            Id = new Guid("23411b0c-59a9-44b2-9ab1-fc3e733ba14a"),
                            Category = "Audit",
                            Description = "Audit capability for Revoke operations on Audit sensitive data",
                            Name = "Audit.Revoke"
                        },
                        new
                        {
                            Id = new Guid("627f238d-e08c-4fe3-895a-ebea821240c1"),
                            Category = "Audit",
                            Description = "Delegated authority for Execute operations on Audit security policies",
                            Name = "Audit.Execute"
                        },
                        new
                        {
                            Id = new Guid("e22dc2fa-b8a8-48e3-b160-cbf3c7c1bcb5"),
                            Category = "Audit",
                            Description = "Limited scope for Schedule operations on Audit integration pipelines",
                            Name = "Audit.Schedule"
                        },
                        new
                        {
                            Id = new Guid("b3a62d75-2f7f-4375-bfed-e247624a20ca"),
                            Category = "Audit",
                            Description = "Compliance-related access to Monitor operations on Audit workflow definitions",
                            Name = "Audit.Monitor"
                        },
                        new
                        {
                            Id = new Guid("29d7b556-047e-4e94-93be-f81fb959b5a2"),
                            Category = "Audit",
                            Description = "Compliance-related access to Configure operations on Audit configuration settings",
                            Name = "Audit.Configure"
                        },
                        new
                        {
                            Id = new Guid("3e7674e0-c7b7-4368-afe1-da53a869f459"),
                            Category = "Audit",
                            Description = "Delegated authority for Bypass operations on Audit reporting modules",
                            Name = "Audit.Bypass"
                        },
                        new
                        {
                            Id = new Guid("20c91abd-9dd0-4712-8f4c-33be0954d7d4"),
                            Category = "Audit",
                            Description = "Temporary permission to Delegate operations on Audit sensitive data",
                            Name = "Audit.Delegate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
