services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      # Only for development purposes, use .env file instead
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employees_manager
    ports:
      - "5432:5432"
    volumes:
      - employees-manager-data:/var/lib/postgresql/data
  employeesmanager.api:
    restart: on-failure
    image: employeesmanager.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Only for development purposes, use .env file instead
      - ConnectionStrings__PostgresConnection=Server=postgres-db:5432;User Id=postgres;Password=password;Database=employees_manager
    depends_on:
      - postgres-db
  web-client:
    image: nginx:alpine
    volumes:
      - ./src/EmployeesManager.Web:/usr/share/nginx/html
    ports:
      - "5001:80"

volumes:
  employees-manager-data: